swagger: '2.0'
info:
  description: The Generic version of DEEP.io Publish Event API
  version: 1.0.1
  title: DEEP.io Publish Event POST API - Generic Version
  contact:
    email: DEEP.io@T-Mobile.com
    name: Deep IO
host: deepio-internal.t-mobile.com
basePath: /deep/v1/events
x-servers:
  - url: https://deepio-internal-development.t-mobile.com/{environment_name}/deep/v1/events/{Your_Event_Name}
    description: All Development
  - url: https://deepio-internal-npe.t-mobile.com/{environment_name}/deep/v1/events/{Your_Event_Name}
    description: All NPE
  - url: https://deepio-internal-plab.t-mobile.com/{environment_name}/deep/v1/events/{Your_Event_Name}
    description: All PLABs
tags:
  - name: event-producer
    description: Sends events to DEEP IO
schemes:
  - https
paths:
  /{event-type}:
    post:
      tags:
        - messaging-controller
      x-api-pattern: CreateInCollection
      summary: This Generic API shall be used by producers to publish events into DEEP.io.
      description: Publishes an event to DEEP IO
      operationId: sendMessageUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: event-type
          in: path
          description: Unique name of the event
          required: true
          type: string
          x-example: Event-123
          pattern: ^[A-Za-z0-9-_]+$
          minLength: 1
          maxLength: 255
        - in: body
          name: event
          description: Event Complex Element
          required: true
          schema:
            $ref: '#/definitions/Event'
        - in: header
          name: Content-Type
          description: Content type passed
          required: true
          type: string
          x-example: application/json
          pattern: ^[ \S]+$
          minLength: 1
          maxLength: 30
        - name: Authorization
          in: header
          description: Bearer token passed created by the client in order to access service api
          required: true
          type: string
          x-example: 'Valid Bearer token '
          pattern: ^[\S ]+$
          minLength: 1
          maxLength: 500
      responses:
        '200':
          description: Message Published Successfully.
          examples:
            application/json:
              message: Message Published Successfully
              status: '200'
              timestamp: Mon Apr 15 23:11:04 UTC 2019
        '201':
          description: Message Broker has not accepted the message but has been Saved and need resubmission from UI. Please Contact Admin to resubmit
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: CREATED
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '201'
        '400':
          description: EventType in URL does not match with eventType in Event Payload,
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: BAD_REQUEST
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '400'
        '401':
          description: EventProducerId and Token senderId doesn't match to publish event in environment.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: UNAUTHORIZED
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '401'
        '403':
          description: ProducerId is not authorized to publish event in env or Event not associated with any Team name in DEEP.io Registry
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: FORBIDDEN
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '403'
        '422':
          description: Event Not Availability check validation failed for Event.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: UNPROCESSABLE_ENTITY
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '422'
        '426':
          description: Access Denied as request is not coming through Deep Gateway. Please use Gateway to publish the message.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: UPGRADE_REQUIRED
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '426'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: INTERNAL_SERVER_ERROR
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '500'
        '501':
          description: Not a valid Request
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: NOT_IMPLEMENTED
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '501'
        '503':
          description: Routing key not defined.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: SERVICE_UNAVAILABLE
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '503'
        '506':
          description: Producer has been disabled, as there is no Event Configuration configured for this Event. Please promote your Event upload valid swagger.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              exception: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              path: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.102'
              message: To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
              error: VARIANT_ALSO_NEGOTIATES
              timestamp: Thu Jun 27 22:35:14 UTC 2019
              status: '506'
      security:
        - Oauth:
            - post:SubmitEvent
definitions:
  Error:
    type: object
    properties:
      exception:
        type: string
        example: |-
          DemoEvent-- Event not available in DEEP.io -- developmentenvironment.
          To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
        description: Error message and information to help resolve the error.
        pattern: ^(.)*$
        minLength: 1
        maxLength: 2000
      path:
        type: string
        example: 'ServletWebRequest: uri=/development/v1/events/DemoEvent;client=198.18.53.10'
        description: Path information and client IP.
        pattern: ^(.)*$
        minLength: 1
        maxLength: 2000
      message:
        type: string
        example: |-
          DemoEvent-- Event not available in DEEP.io -- developmentenvironment.
          To read more details about this error, visit https://qwiki.internal.t-mobile.com/display/DIGEE/Publisher+-+Error+codes and look for error the specific error code.
        description: Error message and information to help resolve the error.
        minLength: 1
        maxLength: 2000
        pattern: ^(.)*$
      error:
        type: string
        example: UNPROCESSABLE_ENTITY
        description: Error code for the error.
        minLength: 1
        maxLength: 255
        pattern: ^(.)*$
      timestamp:
        type: string
        example: Thu Jun 27 22:35:14 UTC 2019
        description: Error message and information to help resolve the error.
        minLength: 10
        maxLength: 100
        format: date-time
      status:
        type: string
        example: '422'
        description: Status code that was returned.
        pattern: ^[\d]*$
        minLength: 3
        maxLength: 3
    description: Error returned
  AuditInfo:
    type: object
    properties:
      accountNumber:
        type: string
        example: F123111
        description: The financial account number identifies the billing account for which the invoice was generated.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      batchId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Batch identification from the event producer, if the event was produced as part of a batch.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      customerId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Uniquely identifies the Customer.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      iamUniqueId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Unique identifier for Identity and Access Management.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      lineId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Uniquely identifies a  line of service.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      orderId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Identifier of order.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      phoneNumber:
        type: string
        example: '1234567890'
        description: The phone number (MSISDN) associated with the line of service.
        minLength: 10
        maxLength: 15
        pattern: ^[a-zA-Z0-9]*$
      universalLineId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: 'ULID - Universal identifier of the LineofService, as defined in Customer Hub. '
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
    description: Audit information used to search specific event. All elements included in this complex element will be searchable in DEEP.io.
    example:
      orderId: 4182f381-9736-11e9-adc6-2f8ba3ffe639
      universalLineId: 4182f381-9736-11e9-adc6-2f8ba3ffe639
  HeaderReference:
    type: object
    properties:
      activityId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Uniquely identifies the business activity definition.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      applicationId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Unique identification of a software application.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      applicationUserId:
        type: string
        example: Alexey211
        description: Application user identification
        minLength: 3
        maxLength: 20
        pattern: ^[A-Za-z0-9-_]+$
      authCustomerId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Customer Id of Tmo customer that is being served/using the application. (Required for non anonymous flows)
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      authFinancialAccountId:
        type: string
        example: 1ZY3101E9000591707
        description: Financial Account Id that the customer that is being served/using the application is working on.  (Required for non anonymous flows)
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      authLineOfServiceId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Line of service Id , within the Financial Account of the customer that is being served/using the application is working on. (Required for non anonymous flows)
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      channelId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Identifies the business unit or sales channel.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      dealerCode:
        type: string
        example: '2033443'
        description: A 7-character, T-Mobile-assigned code used to identify the master dealer contract for commissioning..
        minLength: 1
        maxLength: 256
        pattern: ^[a-zA-Z0-9\-,\.() ]*$
      interactionId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: This Id is going to represent a common transaction id across all service calls made from UI, while completing all business activity needs of a particular customer. Self serve case, generated at time of login and all calls will have this same id. In Assisted channel case, each customer lookup will generate a new interaction Id and carried for all calls made while serving that customer.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      masterDealerCode:
        type: string
        example: '2033443'
        description: A 7-character, T-Mobile-assigned code used to identify the master dealer contract for commissioning.
        minLength: 1
        maxLength: 256
        pattern: ^[a-zA-Z0-9\-,\.() ]*$
      segmentationId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Segmentation Id represents the customer active data center; this is used to route messages to appropriate data center. All financial accounts under customer will be at the same data center.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      senderId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Uniquely identifies the sender.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      sessionId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: A value populated by the sender used to track the transactions that occur during a session, a long-lasting interaction, managed by the sender. GUID generated by partner. Within one session (sessionid) for Rep/system can serve  multiple customers(interactionid) and in a given customer interaction multiple API calls (activityid) will be made to serve the customer. 1 sessionid -> many interactionid 1 interactionid -> many activityid
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      storeId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Unique identifier for the store.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      terminalId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Uniquely identifies a payment terminal in a retail store.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      tillId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: Unique identifier for the retail store terminal till number.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
      timestamp:
        type: string
        format: date-time
        example: '2019-06-28T14:01:40.224-07:00'
        description: A timestamp provided by Sender to track their workflow.  Usually set to the moment when a request is made.
        minLength: 1
        maxLength: 50
      workflowId:
        type: string
        example: 4182f381-9736-11e9-adc6-2f8ba3ffe639
        description: A value populated by the Sender used to track their workflow within the confines of a session. Senders are encouraged to develop a useful scheme. Do not use customer-sensitive information.
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
    description: standard HTTP header elements to be able to deliver them to consumer without interruption
    example:
      masterDealerCode: '2033443'
      workflowId: 4182f381-9736-11e9-adc6-2f8ba3ffe639
  Specifications:
    type: object
    properties:
      name:
        type: string
        example: Key
        description: Name for the name value pair
        minLength: 1
        maxLength: 255
        pattern: ^(.)*$
      value:
        type: string
        example: Value
        description: Value for the name value pair
        minLength: 1
        maxLength: 255
        pattern: ^(.)*$
    description: Name value pair.
  Event:
    type: object
    required:
      - eventProducerId
      - eventTime
      - eventType
      - payload
    properties:
      auditInfo:
        $ref: '#/definitions/AuditInfo'
      eventId:
        type: string
        example: Event-123
        description: Unique identifier for the event generated by the event producer. This element will be searchable in DEEP.io UI
        pattern: ^[A-Za-z0-9-_]+$
        minLength: 1
        maxLength: 255
      eventProducerId:
        type: string
        example: Producer1
        description: Unique identifier for the producer of the event.
        pattern: ^[A-Za-z0-9-_]+$
        minLength: 1
        maxLength: 255
      eventTime:
        type: string
        format: date-time
        example: '2017-03-27T16:20:11.108Z'
        description: The date and time that the event occurred.
        minLength: 10
        maxLength: 30
      eventType:
        type: string
        example: Activation
        description: Event Name that you want to publish
        pattern: ^[A-Za-z0-9-_]+$
        minLength: 1
        maxLength: 255
      eventVersion:
        type: string
        example: '1.0'
        description: version of the event , will be used to distinguish different versions by a consumer
        pattern: ^[\d\.]*$
        minLength: 1
        maxLength: 10
      headerReference:
        $ref: '#/definitions/HeaderReference'
      payload:
        $ref: '#/definitions/Payload'
      specifications:
        type: array
        example: '{}'
        description: added for future reference so can ignore.
        items:
          $ref: '#/definitions/Specifications'
    example:
      auditInfo: '{}'
      eventId: Event-123
      headerReference: '{}'
      payload: {}
      eventVersion: '1.0'
      eventTime: '2017-03-27T16:20:11.108Z'
      event-type: Activation
      eventProducerId: Producer1
      specifications: '{}'
    description: DEEP IO event.
  Payload:
    type: object
    description: Event specific information that can be modeled using APIv2 or inline elements.
    required:
      - scorecard
    properties:
      scorecard:
        $ref: '#/definitions/Scorecard'
  Scorecard:
    type: object
    description: IHAP scorecard payload schema
    required:
      - conversionType
      - version
      - sourceFinancialNumber
      - stage
      - provider
      - status
      - statusCode
      - statusMessage
    properties:
      conversionType:
        type: string
        description: |-
          Conversion project identifier.
           Please refer to the 'Conversion Project Names' tab in the  [Scorecard naming conventions](https://tmobileusa.sharepoint.com/:x:/r/sites/EPOPP/PR212735/PL/Operational%20Readiness/VOCC/02%20Design%20and%20Architecture/IDD/DEEP.io/IHAPScorecardEventSwagger/SuggestedNomenclatureForScorecardEvents.xlsx?d=w38affae6396746b6b4991e21a36cee3e&csf=1&web=1&e=UCUy5k) sheet for the list of recommended application names
        example: EnsembleBillingToSamson
        pattern: ^[A-Za-z0-9-_ ]+$
        minLength: 1
        maxLength: 50
      version:
        type: string
        description: Version of the payload schema
        example: '1.2'
        pattern: ^[\d\.]*$
        minLength: 1
        maxLength: 10
      sourceFinancialNumber:
        type: string
        minLength: 9
        maxLength: 9
        pattern: ^(\d{9})$
        description: Sprint Billing Account Number
        example: '932747120'
      targetFinancialNumber:
        type: string
        minLength: 9
        maxLength: 9
        pattern: ^(\d{9})$
        description: T-Mobile Billing Account Number
        example: '847867567'
      msisdn:
        description: The MSISDN for this activity
        type: number
        minLength: 10
        maxLength: 15
        pattern: ^\d{10,15}$
        example: '8937957676'
      stage:
        description: Current stage in the streaming conversion process
        type: string
        example: injection
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
        enum:
          - ack
          - staging
          - injection
          - postunlock
      activity:
        description: The activity being performed during the current stage of streaming conversion
        type: string
        example: provisioning
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
        enum:
          - provisioning
          - activation
          - deactivation
          - pahupdate
          - paymenthistory
          - collectionhistory
          - credithistory
          - portout
      provider:
        description: |-
          The primary application that publishes this event.
           Please refer to the 'Application Names' tab in the  [Scorecard naming conventions](https://tmobileusa.sharepoint.com/:x:/r/sites/EPOPP/PR212735/PL/Operational%20Readiness/VOCC/02%20Design%20and%20Architecture/IDD/DEEP.io/IHAPScorecardEventSwagger/SuggestedNomenclatureForScorecardEvents.xlsx?d=w38affae6396746b6b4991e21a36cee3e&csf=1&web=1&e=UCUy5k) sheet for the list of recommended application names
        type: string
        example: dbng
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
      onBehalfOf:
        description: |-
          The application on whose behalf the provider publishes the event. For eg. dbng publishing the npe line provisioning status.
           Please refer to the 'Application Names' tab in the  [Scorecard naming conventions](https://tmobileusa.sharepoint.com/:x:/r/sites/EPOPP/PR212735/PL/Operational%20Readiness/VOCC/02%20Design%20and%20Architecture/IDD/DEEP.io/IHAPScorecardEventSwagger/SuggestedNomenclatureForScorecardEvents.xlsx?d=w38affae6396746b6b4991e21a36cee3e&csf=1&web=1&e=UCUy5k) sheet for the list of recommended application names
        type: string
        example: npe
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
      dataSource:
        description: |-
          The source of the data being exchanged during the current activity.
           Please refer to the 'Application Names' tab in the  [Scorecard naming conventions](https://tmobileusa.sharepoint.com/:x:/r/sites/EPOPP/PR212735/PL/Operational%20Readiness/VOCC/02%20Design%20and%20Architecture/IDD/DEEP.io/IHAPScorecardEventSwagger/SuggestedNomenclatureForScorecardEvents.xlsx?d=w38affae6396746b6b4991e21a36cee3e&csf=1&web=1&e=UCUy5k) sheet for the list of recommended application names
        type: string
        example: ensemble
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
      dataProvider:
        description: |-
          The provider of the data being exchanged during the current activity. 
           Please refer to the 'Application Names' tab in the  [Scorecard naming conventions](https://tmobileusa.sharepoint.com/:x:/r/sites/EPOPP/PR212735/PL/Operational%20Readiness/VOCC/02%20Design%20and%20Architecture/IDD/DEEP.io/IHAPScorecardEventSwagger/SuggestedNomenclatureForScorecardEvents.xlsx?d=w38affae6396746b6b4991e21a36cee3e&csf=1&web=1&e=UCUy5k) sheet for the list of recommended application names
        type: string
        example: ace
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
      status:
        description: Status of the activity - success or failure
        type: string
        example: S
        minLength: 1
        maxLength: 5
        pattern: ^[A-Za-z0-9-_]+$
        enum:
          - S
          - F
      statusCode:
        description: Status code for the activity. 0 for success, other numbers for failure. In case of failure, the error details array will have detailed error information
        type: string
        example: 2001
        minLength: 1
        maxLength: 10
        pattern: ^[A-Za-z0-9-_]+$
      statusMessage:
        description: Status message in free format
        type: string
        example: Line provisioning failed
        pattern: ^[ \S]+$
        minLength: 1
        maxLength: 1000
      dataReceivedAt:
        type: string
        format: date-time
        example: '2021-01-27T16:20:11Z'
        description: The timestamp (in UTC) that the application received the data for the activity
        minLength: 10
        maxLength: 30
      dataProcessedAt:
        type: string
        format: date-time
        example: '2021-01-27T16:25:11Z'
        description: The timestamp (in UTC) that the application processed the data for the activity
        minLength: 10
        maxLength: 30
      meta:
        description: Meta details. Key-value pairs that contain additional information about the conversion activity
        example:
          - param: totalBans
            value: '1'
          - param: totalAmount
            value: '2050'
        type: array
        items:
          $ref: '#/definitions/MetaDetails'
      errorDetails:
        description: The error details in case of failure
        example:
          - code: '20018'
            severity: critical
            system: npe
            category: Mandatory objects missing in request payload
            message: Missing locationCordinates Object in e911Address object
        type: array
        items:
          $ref: '#/definitions/ErrorDetails'
      records:
        description: Record details
        type: object
        required:
          - total
        properties:
          total:
            description: Total count of records
            type: integer
            example: 10
            minLength: 1
            maxLength: 5
            pattern: ^[\d]*$
          meta:
            description: Meta details. Key-value pairs that contain additional information about the records
            example:
              - param: eppPaymentID
                value: '22232'
              - param: dpsPaymentID
                value: '11122232'
            type: array
            items:
              $ref: '#/definitions/MetaDetails'
          record:
            description: Array of records with details
            type: array
            items:
              $ref: '#/definitions/RecordDetails'
      subscribers:
        description: Subscriber details
        type: object
        required:
          - total
        properties:
          total:
            description: Total count of subscribers
            type: integer
            example: 10
            minLength: 1
            maxLength: 5
            pattern: ^[\d]*$
          meta:
            description: Meta details. Key-value pairs that contain additional information about the subscribers
            example:
              - param: totalSubscibers
                value: '2'
            type: array
            items:
              $ref: '#/definitions/MetaDetails'
          subscriber:
            description: Array of subscriber details
            type: array
            items:
              $ref: '#/definitions/SubscriberDetails'
  MetaDetails:
    type: object
    description: Meta details. Key-value pairs that contain additional information
    required:
      - param
      - value
    properties:
      param:
        type: string
        description: Key name
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_ ]+$
        example: totalAmount
      value:
        type: string
        description: Value for the corresponding key
        minLength: 1
        maxLength: 255
        pattern: ^[ \S]+$
        example: '2050'
  ErrorDetails:
    type: object
    description: Error details
    required:
      - code
      - system
      - message
    properties:
      code:
        description: Error code
        type: string
        example: 20018
        minLength: 1
        maxLength: 10
        pattern: ^[A-Za-z0-9-_]+$
      severity:
        description: Error severity
        type: string
        example: critical
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
        enum:
          - critical
          - warning
          - info
      system:
        description: |-
          The source system from which the error originated.
           Please refer to the 'Application Names' tab in the  [Scorecard naming conventions](https://tmobileusa.sharepoint.com/:x:/r/sites/EPOPP/PR212735/PL/Operational%20Readiness/VOCC/02%20Design%20and%20Architecture/IDD/DEEP.io/IHAPScorecardEventSwagger/SuggestedNomenclatureForScorecardEvents.xlsx?d=w38affae6396746b6b4991e21a36cee3e&csf=1&web=1&e=UCUy5k) sheet for the list of recommended application names
        type: string
        example: npe
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
      category:
        description: Error category
        type: string
        example: Mandatory objects missing in request payload
        minLength: 1
        maxLength: 255
        pattern: ^[A-Za-z0-9-_ ]+$
      message:
        description: Detailed error message
        type: string
        example: Missing locationCordinates Object in e911Address object
        minLength: 1
        maxLength: 1000
        pattern: ^[ \S]+$
  RecordDetails:
    type: object
    description: Record details
    required:
      - status
      - statusCode
      - statusMessage
    properties:
      recordSourceId:
        description: The id of the source record
        type: string
        minLength: 1
        maxLength: 15
        pattern: ^[A-Za-z0-9-_]+$
        example: '123001'
      recordTargetId:
        description: The id of the target record
        type: string
        minLength: 1
        maxLength: 15
        pattern: ^[A-Za-z0-9-_]+$
        example: '500002'
      msidsn:
        description: The MSISDN associated with the line of service
        type: number
        minLength: 10
        maxLength: 15
        pattern: ^\d{10,15}$
        example: '8937957676'
      sourceSubscriberId:
        description: Sprint subscriber id
        type: string
        minLength: 1
        maxLength: 15
        pattern: ^\d{1,15}$
        example: '932747120'
      targetSubscriberId:
        description: T-Mobile subscriber id
        type: string
        minLength: 1
        maxLength: 15
        pattern: ^\d{1,15}$
        example: '932747120'
      status:
        description: Status of the activity - success or failure
        type: string
        example: S
        minLength: 1
        maxLength: 5
        pattern: ^[A-Za-z0-9-_]+$
        enum:
          - S
          - F
      statusCode:
        description: Status code for the activity. 0 for success, other numbers for failure
        type: string
        example: 0
        minLength: 1
        maxLength: 10
        pattern: ^[A-Za-z0-9-_]+$
      statusMessage:
        description: Status message in free format
        type: string
        example: Ok
        pattern: ^[ \S]+$
        minLength: 1
        maxLength: 1000
      meta:
        description: Meta details. Key-value pairs that contain additional information about the record
        example:
          - param: eppPaymentID
            value: '22232'
          - param: dpsPaymentID
            value: '11122232'
        type: array
        items:
          $ref: '#/definitions/MetaDetails'
      errorDetails:
        description: The error details in case of failure
        example:
          - code: '20018'
            severity: critical
            system: npe
            category: Mandatory objects missing in request payload
            message: Missing locationCordinates Object in e911Address object
        type: array
        items:
          $ref: '#/definitions/ErrorDetails'
  SubscriberDetails:
    type: object
    description: Record details
    required:
      - status
      - statusCode
      - statusMessage
    properties:
      sourceSubscriberId:
        description: Sprint subscriber id
        type: string
        minLength: 1
        maxLength: 15
        pattern: ^\d{1,15}$
        example: '932747120'
      targetSubscriberId:
        description: T-Mobile subscriber id
        type: string
        minLength: 1
        maxLength: 15
        pattern: ^\d{1,15}$
        example: '932747120'
      msidsn:
        description: The MSISDN associated with the line of service
        type: number
        minLength: 10
        maxLength: 15
        pattern: ^\d{10,15}$
        example: '8937957676'
      status:
        description: Status of the activity - success or failure
        type: string
        example: S
        minLength: 1
        maxLength: 5
        pattern: ^[A-Za-z0-9-_]+$
        enum:
          - S
          - F
      statusCode:
        description: Status code for the activity. 0 for success, other numbers for failure
        type: string
        example: 0
        minLength: 1
        maxLength: 10
        pattern: ^[A-Za-z0-9-_]+$
      statusMessage:
        description: Status message in free format
        type: string
        example: Ok
        pattern: ^[ \S]+$
        minLength: 1
        maxLength: 1000
      action:
        description: The action being performed for the subscriber
        type: string
        example: activation
        minLength: 1
        maxLength: 50
        pattern: ^[A-Za-z0-9-_]+$
        enum:
          - provisioning
          - activation
          - deactivation
          - pahupdate
          - paymenthistory
          - collectionhistory
          - credithistory
          - portout
      actionTarget:
        description: |-
          The target application for the action
           Please refer to the 'Application Names' tab in the  [Scorecard naming conventions](https://tmobileusa.sharepoint.com/:x:/r/sites/EPOPP/PR212735/PL/Operational%20Readiness/VOCC/02%20Design%20and%20Architecture/IDD/DEEP.io/IHAPScorecardEventSwagger/SuggestedNomenclatureForScorecardEvents.xlsx?d=w38affae6396746b6b4991e21a36cee3e&csf=1&web=1&e=UCUy5k) sheet for the list of recommended application names
        type: string
        example: epp
        minLength: 1
        maxLength: 30
        pattern: ^[A-Za-z0-9-_]+$
      meta:
        description: Meta details. Key-value pairs that contain additional information about the conversion activity
        example:
          - param: totalBans
            value: '1'
          - param: totalAmount
            value: '2050'
        type: array
        items:
          $ref: '#/definitions/MetaDetails'
      errorDetails:
        description: The error details in case of failure
        example:
          - code: '20018'
            severity: critical
            system: npe
            category: Mandatory objects missing in request payload
            message: Missing locationCordinates Object in e911Address object
        type: array
        items:
          $ref: '#/definitions/ErrorDetails'
securityDefinitions:
  Oauth:
    type: oauth2
    description: JWT/Oauth2 instructions https://qwiki.internal.t-mobile.com/pages/viewpage.action?pageId=152594457
    tokenUrl: https://api.enterprise.apigee.com/v1/organizations/{domain}/e/{environment}/caches/
    flow: application
    scopes:
      post:SubmitEvent: Submit event an event to DEEP IO.
